version: '3.3'
services:
  mb_db:
    container_name: mb_db
    image: mariadb:10.7.4
    environment:
      MYSQL_DATABASE: 'soda'
      MYSQL_USER: 'soda'
      MYSQL_PASSWORD: 'soda'
      MYSQL_ROOT_PASSWORD: 'soda'
    volumes:
      - '../../../../data_prod/mb_db_prod/:/var/lib/mysql'
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - soda-network

networks:
  soda-network:
    external: false
    name: soda-network
