version: '3.3'
services:
  mb_admin:
    build:
      context: ../../../
      dockerfile: ./infrastructure/Dockerfile
    image: giangsoda/mb:0.0.1
    container_name: mb_admin
    env_file:
      - ../../../.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - soda-network
    command: node dist/main

  mb_api:
    image: giangsoda/mb:0.0.1
    container_name: mb_api
    env_file:
      - ../../../.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - soda-network
    command: node dist/api

networks:
  soda-network:
    external: false
    name: soda-network
