version: '3.3'
services:
  nest_base_stg:
    image: giangsoda/nest-base:0.0.1
    container_name: nest_base_stg
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always
    networks:
      - soda-network

  nest_base_db_stg:
    container_name: nest_base_db_stg
    image: mariadb:10.7.4
    environment:
      MYSQL_DATABASE: 'soda'
      MYSQL_USER: 'soda'
      MYSQL_PASSWORD: 'soda'
      MYSQL_ROOT_PASSWORD: 'soda'
    volumes:
      - './maria-db:/var/lib/mysql'
    restart: always
    networks:
      - soda-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


networks:
  soda-network:
    external: false
    name: soda-network
